image: debian:buster-slim

stages:
  - build
  - test

pages:
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends gettext python3-babel python3-pip git python3-inifile python3-dev python3-setuptools python3-venv python3-openssl python3-cryptography i18nspector -y
    - pip3 install babel
    - pip3 install wheel
    - pip3 install lektor
    - rm -rf i18n
    - git clone https://git.torproject.org/translation.git i18n
    - cd i18n && git checkout tbmanual-contentspot && cd ..
    - rm -rf lego
    - git clone https://git.torproject.org/project/web/lego.git lego
    - cd lego && git checkout master && git pull && cd ..
    - rm -rf public
    - lektor plugins reinstall
    - lektor build --output-path public && lektor build --output-path public

  artifacts:
    paths:
      - public
      - i18n
  only:
    - translations
check_l10n:
  stage: test
  script: 
    - if [[ $(grep -r '] (' i18n/*.po) ]] ; then echo "TEST FAILED: broken links" && `grep -r '] (' i18n/*.po >&2` ; else echo "no broken links"; fi || true
    - allow_failure: true
